name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: entry project dir
      run:  cd AutoTools/AutoconfDemo
    - name: pwd
      run:  pwd
    - name: configure
      run: ./AutoTools/AutoconfDemo/configure
    - name: make
      run: ./AutoTools/AutoconfDemo/make
    - name: make check
      run: ./AutoTools/AutoconfDemo/make check
    - name: make distcheck
      run: ./AutoTools/AutoconfDemo/make distcheck
